### ISSUE TITLE
global keyboard capture? (possible feature bounty)

### ISSUE THREAD

**Issue by exts** [Adrian-Samoticha/macos_window_utils.dart#1]
I've longed for an easy way to easily capture global keyboard hotkeys for apps like screen capture (think ShareX) etc... looking to start a bounty for this (not sure how, but definitely need this lol)

**Comment by exts** [comment]
Started a bounty for this, something I need not want lol. I may add more if there's some interest. 

https://app.bountysource.com/issues/115076839-global-keyboard-capture-possible-feature-bounty

**Comment by Adrian-Samoticha** [comment]
I have not tried it out myself, but have you checked out the [global_shortcuts](https://pub.dev/packages/global_shortcuts) package? It seems to be doing exactly what you're asking for.

**Comment by exts** [comment]
> I have not tried it out myself, but have you checked out the [global_shortcuts](https://pub.dev/packages/global_shortcuts) package? It seems to be doing exactly what you're asking for.

Looks like it's only for macos atm

**Comment by Adrian-Samoticha** [comment]
> Looks like it's only for macos atm

Well, so is macos_window_utils (hence the name).

**Comment by exts** [comment]
I just noticed. Well, Guess I'm going to have to do somethibg with this bounty lol thanks for that repo link

**Comment by Adrian-Samoticha** [comment]
If you are fine with a solution that works on Windows as well, there is a tool called [keyviz](https://github.com/mulaRahul/keyviz) which visualizes your keystrokes in real-time. Perhaps you could check out how it does that. That said, I am not aware of any solution that works on Linux as well.

**Comment by exts** [comment]
I just found a new library actually https://pub.dev/packages/keyboard_event does exactly what I want :) I appreciate it, gonna try donating over that way. Gl w/ your project!

**Comment by Adrian-Samoticha** [comment]
I just checked and this is exactly the library that keyviz uses, so yeah. I hope that one works out for you. :)
