### ISSUE TITLE
All window styles doesn't work after upgrading Flutter to 3.7.0

### ISSUE THREAD

**Issue by damywise** [Adrian-Samoticha/macos_window_utils.dart#12]
When downgraded, the window styles works normally.
## Screenshot:
<img width="912" alt="image" src="https://user-images.githubusercontent.com/25608913/214541726-5c28aa52-4e4c-4575-81a1-6c9a2d29f283.png">

**Comment by Adrian-Samoticha** [comment]
It appears that Flutter now adds a black background to the window and I cannot find a way to remove it. Not even `BlendMode.clear` helps.

**Comment by jinfagang** [comment]
@Adrian-Samoticha  Does it able to support flutter 3.7? If not, I will lost everything depends on your package.
